openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
  contact:
    email: polley@predic8.de
  description: Quotation API
servers:
  - url: https://api.server.test/v1
tags:
  - name: RFQ
paths:
  /rfqs:
    post:
      operationid: getQuote
      tags:
      - RFQ
      description: get a quote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quotation"
      responses:
        '200':
          description: OK

components:
  schemas:
    Quotation:
      type: object
      properties:
        id:
          type: integer
        product:
          type: string
        quantity:
          type: integer
        price:
          type: number
        shipment:
          type: string
        mode:
          type: string
